### ISSUE TITLE
Action Failed, maybe due to its version

### ISSUE THREAD

**Issue by kanition** [xu-cheng/texlive-action#16]
My [action](https://github.com/kanition/pbrtbook/actions/runs/8269595832/job/22704289528) failed. Here is the log. It seems that the version is not configured correctly.
Could you help me?
[Workflow file](https://github.com/kanition/pbrtbook/actions/runs/8269595832/workflow)

Log
`
tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
`

**Comment by xu-cheng** [comment]
This is due to TeXLive 2024 release. Usually, you don't need to run tlmgr update as the docker image is updated monthly. The problem should be fixed now.

**Comment by kanition** [comment]
Thank you very much
