### ISSUE TITLE
Found biblatex control file version 3.11, expected version 3.10.

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/texlive-action#17]
I'm getting the following error running `latexmk` at the top level of this repo https://github.com/paddyroddy/phd-thesis. The logs in question are https://github.com/paddyroddy/phd-thesis/actions/runs/8512615536/job/23337820498?pr=41. Compiling locally works fine with `latexmk` version `Latexmk, John Collins, 31 Jan. 2024. Version 4.83`.

```sh
luaotfload | db : Font names database not found, generating new one.
luaotfload | db : This can take several minutes; please be patient.This is LuaHBTeX, Version 1.18.0 (TeX Live 2024) 
 system commands enabled.
sh: tput: not found
This is LuaHBTeX, Version 1.18.0 (TeX Live 2024) 
 system commands enabled.
sh: tput: not found
Latexmk: Missing bbl file 'thesis.bbl' in following:
 No file thesis.bbl.
Latexmk: Getting log file 'thesis.log'
Latexmk: Run number 1 of rule 'biber thesis'
Latexmk: ====Undefined refs and citations with line #s in .tex file:
  Reference `fig:chapter5_region' on page 1 undefined on input line 78
  Citation 'Simons2006' on page 12 undefined on input line 4
Biber error: [233] Utils.pm:410> ERROR - Error: Found biblatex control file version 3.11, expected version 3.10.
  Citation 'Turcotte1981' on page 12 undefined on input line 4
  Citation 'Ramamoorthi2004' on page 12 undefined on input line 4
  Citation 'Ramamoorthi2004' on page 12 undefined on input line 4
  Citation 'Bennett1996' on page 12 undefined on input line 4
  Citation 'Gorry1990' on page 12 undefined on input line 11
 And 903 more --- see log file 'thesis.log'
Latexmk: Sometimes, the -f option can be used to get latexmk
  to try to force complete processing.
  But normally, you will need to correct the file(s) that caused the
  error, and then rerun latexmk.
  In some cases, it is best to clean out generated files before rerunning
  latexmk after you've corrected the files.
Latexmk: Error return from 'biber thesis'
I will add to its source list, anything cached from analysis of bcf file.
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 347 reference(s)
  Latex failed to resolve 563 citation(s)
Collected error summary (may duplicate other messages):
  biber thesis: Biber errors: See file 'thesis.blg'
```

**Comment by xu-cheng** [comment]
Please provide a [minimal working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) to demonstrate your problem.

Looks like a LaTeX usage problem rather one of this action. Please consider to seek help from reddit or TeX.stackexchange. The issue page is only to report problem related to this action.

Also, make sure you build the document from a clean environment. Looks to me you have some stale LaTeX temporary files which cause the issue.

**Comment by xu-cheng** [comment]
Ok, after close looks, this seems to be caused by out-of-sync of biber and biblatex in the latest docker image. I have roll backed the image to the last working one. Please try again. The issue should have been resolved.

**Comment by paddyroddy** [comment]
I was pretty sure this was a new release, as it was working for me 2 weeks ago. Will try later, but consider this completed!

**Comment by paddyroddy** [comment]
I think this might be happening again?
