### ISSUE TITLE
!Latex Error: 'Sweave.sty' not found

### ISSUE THREAD

**Issue by gaborbernat** [xu-cheng/texlive-action#18]
With https://github.com/gaborbernat/statistics_latex/actions/runs/11018575092/job/30599162354?pr=1 and code https://github.com/gaborbernat/statistics_latex/pull/1/files

https://tex.stackexchange.com/questions/153193/latex-error-sweave-sty-not-found says this might be an upstream limitation. Ideas how to work around this issue within this action?

**Comment by xu-cheng** [comment]
It seems that the file is not part of Texlive. You should provide the package on your own. In the future, please consider to use Google, Reddit, or Tex.StackExchange to ask general questions related to LaTeX. The issue page is resolved to the problem specified to this action only.

**Comment by gaborbernat** [comment]
> It seems that the file is not part of Texlive. You should provide the package on your own. In the future, please consider to use Google, Reddit, or Tex.StackExchange to ask general questions related to LaTeX. The issue page is resolved to the problem specified to this action only.

I believe is related. If you check the issue there's a workaround specified but unclear how I apply that patch within the GitHub Action.

**Comment by xu-cheng** [comment]
Again the requested package is simply not distributed by TeXLive. The stackexchange link above is related to how to install the additional package to the local TeXLive to be used in a system wise manner. For your case, you should simply put the corresponding package files in the same directory of the LaTeX file. No other workaround is required.
