### ISSUE TITLE
How to mark a build as failed for non-zero exit code but proceed in following steps

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/texlive-action#2]
hi, thanks for the action. I'm using it to run `chktex` on all files and then `latexmk` on them i.e.

```
- name: Run chktex
  uses: xu-cheng/texlive-action/full@v1
  with:
      run: |
          for file in $(ls *.tex); do \
          echo $file; \
          chktex $file | tee /dev/stderr | (! grep -q ^); \
          done

- name: Build PDF
  uses: xu-cheng/texlive-action/full@v1
  with:
      run: |
          for file in $(ls *.tex); do \
          echo $file; \
          latexmk -quiet -pdf $file; \
          done
```

but at the moment if `chktex` has errors the build is still marked as passed, how can I stop this?

I would still like the PDFs built (ideally) if the `chktex` step fails.

Sorry if this is obvious, I'm new to GH actions

**Comment by xu-cheng** [comment]
* You can use bash command `set -e` to make scripts return failure.
* You can compile pdf files before running `chktex`.

In the future, please only open issue that related to the bug report or feature request. General problems about how to use GitHub Actions should be asked in stackoverflow or other Q&A websites.

**Comment by paddyroddy** [comment]
if anyone comes across this, the problem was the for loop hiding the error. `if: always()` allows the next step to continue

```
- name: Run chktex
  uses: xu-cheng/texlive-action/full@v1
  with:
      run: |
          set -e;
          for file in $(ls *.tex); do \
          echo $file; \
          chktex $file | tee /dev/stderr | (! grep -q ^); \
          done

- name: Build PDF
  if: ${{ always() }}
  uses: xu-cheng/texlive-action/full@v1
  with:
      run: |
          for file in $(ls *.tex); do \
          echo $file; \
          latexmk -quiet -pdf $file; \
          done
```

**Comment by xu-cheng** [comment]
FYI, I have just made `set -e` be passed to bash as default now. So you can omit `set -e` in your `run` input.

**Comment by paddyroddy** [comment]
thanks!
