### ISSUE TITLE
support for CJK fonts

### ISSUE THREAD

**Issue by e71828** [xu-cheng/texlive-action#3]
Thanks a lot for your work. 

How can I do if I want to compile .tex  in Chinese?

**Comment by xu-cheng** [comment]
This action allows you to run arbitrary texlive command. For CJK, it is often achieved by xelatex + xeCJK or lualatex + luatex-ja. Please refer to their documents for usage. Also, it is recommended to ask general latex usage questions in other places such as TEX.stackexchange.
