### ISSUE TITLE
texlive 2021

### ISSUE THREAD

**Issue by tjbcg** [xu-cheng/texlive-action#4]
With TeXlive 2021 coming out on April 1st, tlmgr refuses to install packages with the following error message:

```
tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```
It turns out I don't need the package I was installing from tlmgr, but I thought I'd better let you know.

**Comment by xu-cheng** [comment]
I just rebuilt the docker image to TeXLive 2021. I think the problem should be solved in the process.
