### ISSUE TITLE
How to delete biber cache?

### ISSUE THREAD

**Issue by paddyroddy** [xu-cheng/texlive-action#5]
I believe I'm encountering the problem you were experiencing here https://github.com/plk/biber/issues/312. I cannot replicate the error locally that I'm getting via this CI. How can I resolve it? Is there a way to force cache to be deleted every run say?

**Comment by xu-cheng** [comment]
Please show a minimum work example and its logs to demonstrate your problem. 

If it is truly the issue you linked, why cannot you just run the delete command every time you run this action? Simply run https://github.com/plk/biber/issues/312#issuecomment-762350156 before compiling your tex document.

**Comment by paddyroddy** [comment]
Okay I've solved this problem, and it wasn't cache related. The logs from the action were suggesting a reference/citation issue
<img width="741" alt="image" src="https://user-images.githubusercontent.com/15052188/123118081-3bb76b00-d43a-11eb-80f2-d1c80b141701.png">

I ran the docker image locally `ghcr.io/xu-cheng/texlive-full:latest` and built it in there and isolated the issue to `pgfplots` and have basically solved this by running `latexmk -lualatex <file>` rather than `latexmk -pdf <file>` https://tex.stackexchange.com/q/7953/160320

I cannot explain why I was having `TeX capacity exceeded, sorry [main memory size=]` error in the image and not locally. I looked at `/opt/texlive/texdir/texmf-dist/web2c/texmf.cnf` in the image and appeared to have the same config as my local `/usr/local/texlive/2021/texmf-dist/web2c/texmf.cnf`. Locally, I do not need to use `lualatex`.
