### ISSUE TITLE
"The following actions uses node12 which is deprecated and will be forced to run on node16"

### ISSUE THREAD

**Issue by MoralCode** [xu-cheng/texlive-action#9]
When running a workflow with this action, im getting a warning about "The following actions uses node12 which is deprecated and will be forced to run on node16" which links to this blog post: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

It seemed to run fine, so presumably its an easy/non-breaking upgrade but wanted to report it just in case 

Thanks for the easy to use extension!

**Comment by xu-cheng** [comment]
I don’t believe the error is caused by this action, which is based on docker not node.

**Comment by MoralCode** [comment]
wow, I really was not paying attention on that one - the error was actually referring to actions/checkout@v2, not this one.

Sorry for wasting your time
